### ISSUE TITLE
Shiny

### ISSUE THREAD

**Issue by Dougeee** [Dougeee/-#1]
shinydashboard()支持shiny自带的所有~Input()对象,
这些对象同样也能放入box中。
所有Input对象：

actionButton(), 激活按钮。

actionLink(), 激活链接。

checkboxInpu()， 勾选框。

checkboxGroupInput(), 勾选组合框。

dateInput(), 日期选择框。

dateRangeInput(), 日期范围选择框。

fileInput()，上传文件框。

downloadButton(), 下载数据。

numericInput(), 数字选择框。

passwordInput(), 密码输入框。

radioButtons(), 单选按钮。

selectInput(), 选择框。

sliderInput(), 滑动条。

submitButton(), 提交按钮。

textInput(), 文本输入框。

输出需要一对组合函数，在UI端使用~Output(), 在server端使用render~(),
2者通过变量名进行匹配。shinydashboard同样支持所有shiny自带的输出组合。

所有输出组合:

renderPlot() 与 plotOutput(), 绘图输出。

renderText() 与 textOutput(), 文本输出。

renderPrint() 与 verbatimTextOutput(), 打印输出。

renderTable() 与 tableOutput(), 以HTML表格形式输出。

renderImage() 与 imageOutput(), 读取图片输出。

renderDataTable() 与 dataTableOutput(), 交互式表格输出，来自DT包。

renderUI() 与 uiOutput()/htmlOutput(), 当作html语法输出。

**Comment by Dougeee** [comment]
cht

**Comment by TiffanyZsh** [comment]
How

**Comment by feynmantu** [comment]
aloha

**Comment by CaptainJTT** [comment]
Selamat malam

**Comment by Dougeee** [comment]
傻逼

**Comment by TiffanyZsh** [comment]
Candles=vector("numeric",length=length(JJJ$Age))
k<-0
for (Age in JJJ$Age){
k<-k+1
c<-0
for (n in 0:Age){
c<-c+n
}
Candles[k]<-c
}
Candles<-data.frame(Name=JJJ$Name,Age=JJJ$Age,Candles)

**Comment by Dougeee** [comment]
library('shiny')

ui <- fluidPage(
  numericInput(inputId = 'N', "Sample Size", min = 1, max = 10000,  value = 10),
  sliderInput(inputId = 'p', "P( X = 1 )", min = 0, max = 1, value = 0.5),
  textInput(inputId = 'title', label = 'Write a label', value = 'Plot'),
  actionButton(inputId ='go', label='Go'),
  plotOutput(outputId = 'LLW'),
  verbatimTextOutput(outputId = 'stats')
)

server <- function(input, output){
  observeEvent(input$go, {
    output$LLW <- renderPlot({
      x <- rbinom(input$N, 1, input$p)
      
      par(mfrow = c(1, 2))
      barplot(table(x)/input$N, ylim = c(0, 1), ylab = 'Frequency')
      plot(cumsum(x)/c(1:input$N), type = 'l', ylab = 'Y', xlab = 'Trials', main = input$title)
      abline(h = input$p)
    })
    
    output$stats <- renderPrint({
      summary(rbinom(input$N, 1, input$p))
    })
  }
  
  )
}

shinyApp(ui = ui, server = server)

**Comment by ciya2326** [comment]
是我TTT

**Comment by Han-Bowen** [comment]
hello

**Comment by David-haohao** [comment]
good moring

**Comment by Dougeee** [comment]
https://mp.weixin.qq.com/s?__biz=MzA3MTM3NTA5Ng==&mid=2651060784&idx=1&sn=068d7cf8f563028515f05f196fc30691&chksm=84d9dba7b3ae52b172bb5f3b0332340486391129431e7a302902698900bc9b8157344a54d528&scene=21#wechat_redirect

**Comment by Dougeee** [comment]
library(shiny)

ui <- fluidPage(
  sliderInput(inputId="k", label='Slope \\(m\\)', value=10, min=1, max=10000, step=1), 
  plotOutput("myplot")
)

N_value <- function(k){
  k_list <- rep(0,k)
  for(i in 1:k){
    x <- runif(i,min = 0, max = 1)
    y <- runif(i,min = 0, max = 1)
    N_k <- length(x[x**2 +y**2 < 1])
    k_list[i] <- (N_k*4) / i
  }
  return(k_list)
}

server <- function(input, output){
  
  output$myplot <- renderPlot({
    xp <- 1:input$k
    plot(xp, N_value(input$k), ylim=c(0, 4), ylab="y")
  })}


shinyApp(ui = ui, server = server)

**Comment by Dougeee** [comment]
ggplot2  几何函数指定图的类型

geom_bar() 条形图 color、fill、alpha 
geom_boxplot() 箱线图 color、fill、alpha、notch、width 
geom_density() 密度图 color、fill、alpha、linetype 
geom_histogram() 直方图 color、fill、alpha、linetype、binwidth 
geom_hline() 水平线 color、alpha、linetype、size 
geom_jitter() 抖动点 color、size、alpha、shape 
geom_line() 线图 colorvalpha、linetype、size 
geom_point() 散点图 color、alpha、shape、size 
geom_rug() 地毯图 color、side 
geom_smooth() 拟合曲线 method、formula、color、fill、linetype、size 
geom_text() 文字注解 很多，参见函数的“帮助”
geom_violin() 小提琴图 color、fill、alpha、linetype 
geom_vline() 垂线 color、alpha、linetype、size

**Comment by Dougeee** [comment]
sliderInput(inputId="N", label='N:', value=1000, min=100, max=100000),
  sliderInput(inputId="a", label='a:', value=1, min=-5, max=5),
  sliderInput(inputId="s ", label='s:', value=2, min=0.1, max=5),
  sliderInput(inputId="b", label='N:', value=3, min=0.1, max=3),

**Comment by TiffanyZsh** [comment]
整个代码

**Comment by TiffanyZsh** [comment]
ui <- fluidPage(
  sliderInput(inputId="N", label='N:', value=1000, min=100, max=100000),
  sliderInput(inputId="a", label='a:', value=1, min=-5, max=5),
  sliderInput(inputId="s ", label='s:', value=2, min=0.1, max=5),
  sliderInput(inputId="b", label='N:', value=3, min=0.1, max=3),
)
server <- function(input, output) {}
shinyApp(ui = ui, server = server)

**Comment by David-haohao** [comment]
Q1
library(shiny)
ui <- fluidPage(
  titlePanel("21032116 Random Sample"),
  sliderInput(inputId="n", label='N', value=1000, min=100, max=100000, step=10), 
  sliderInput(inputId="a", label='A', value=1, min=-5, max=5, step=.1),
  sliderInput(inputId="s", label='S', value=2, min=0.1, max=5, step=.1),
  sliderInput(inputId="b", label='B', value=3, min=0.1, max=3, step=.1),
  plotOutput("myplot")
)

server <- function(input, output){
  output$myplot <- renderPlot({
    x <- rnorm(input$n,input$a,input$s)
    y <- runif(input$n,0,input$b)
    plot(x,y,type = 'p',xlim = c(-10,10),ylim = c(-1,4), ylab = 'Y', xlab = 'x', main = input$title)
  })
}

shinyApp(ui = ui,server = server)

**Comment by ciya2326** [comment]
1不是N个随机生成的点吗

**Comment by Dougeee** [comment]
我1参数错误、

**Comment by Dougeee** [comment]
## 1

library(shiny)

# Define UI for  app ----

ui <- fluidPage(
  titlePanel("2017208"),
  mainPanel(
  


  sliderInput(inputId="N", label='N:', value=1000, min=100, max=100000,step=1),
  sliderInput(inputId="a", label='a:', value=1, min=-5, max=5,step=0.1),
  sliderInput(inputId="s ", label='s:', value=2, min=0.1, max=5,step=0.1),
  sliderInput(inputId="b", label='N:', value=3, min=0.1, max=3,step=0.1),



  plotOutput("myplot")
  
  )
)


# Define server logic  ----

server <- function(input, output) {
  output$myplot <- renderPlot({
    x <- rnorm(input$N,input$a,input$s)
    y <- runif(input$N,0,input$b)
    plot(x,y,type = 'p',xlim = c(-10,10),ylim = c(-1,4), ylab = 'Y', xlab = 'x', main = input$title)
  })
}

# Run the application 
shinyApp(ui = ui, server = server)

**Comment by feynmantu** [comment]
Q1

ui <- fluidPage(
  sliderInput(inputId="N", label='Size \\(N\\)', value=1000, min=100, max=10000), 
  sliderInput(inputId="a", label='x mean \\(a\\)', value=1, min=-5, max=5, step=.1), 
  sliderInput(inputId="s", label='x standard deviation \\(s\\)', value=2, min=0, max=1.5, step=.1), 
  sliderInput(inputId="b", label='y max \\(b\\)', value=3, min=0, max=1.3, step=.1), 
  plotOutput("myplot")
)

get_x <- function(N,a,s){
  x <- rnorm(N, a, s)
  return(x)
}
get_y <- function(N,b){
  y <- runif(N,min = 0, max = b)
}

server <- function(input, output) {

  output$myplot <- renderPlot({
    plot(get_x(input$N,input$a,input$s), get_y(input$N,input$b), ylim=c(-1, 4),xlim=c(-10, 10), ylab="y", lwd=3)

  })}
shinyApp(ui = ui, server = server)

**Comment by TiffanyZsh** [comment]
第二题

**Comment by Dougeee** [comment]
第四有吗

**Comment by ciya2326** [comment]
来不及

**Comment by Dougeee** [comment]
## 2
iris$Sepal.Length
ui <- fluidPage(
  titlePanel("2017208,Scatterplot for iris data"),
  
  # Input ----
 
  sliderInput(inputId="a", label='N:', value=.3, min=0, max=1),
  sliderInput(inputId="b", label='a:', value=.6, min=-0.5, max=1.5),

  
  
  # Output
  plotOutput("myplot")
  
)

server <- function(input, output) {
  output$myplot <- renderPlot({
    SepalC  <-  input$a*iris$Sepal.Length+(1-input$a)*iris$Sepal.Width
    PetalC  <-  input$b*iris$Petal.Length+(1-input$b)*iris$Petal.Width
    SP <- iris$Species
    print(SepalC)
    print(PetalC)
    
    plot(SepalC,PetalC)

  })
  pdf("irisplot")
  dev.off( )
  
  
}
shinyApp(ui = ui, server = server)

**Comment by feynmantu** [comment]
Q3
temp2021 <- read.csv("C:/Users/18059/Downloads/temp2021-3 (1).csv", sep="")

library(shiny)

ui <- fluidPage(
  numericInput("k", label = h3("Numeric input"), value = 3),
  plotOutput("myplot"),
  
  hr(),
  fluidRow(column(3, verbatimTextOutput("value")))
)

get_ts <- function(a,temp){
  time <- ts(temp[,a], frequency=12, start=c(1978,12))
  return(time)
}


server <- function(input, output) {

  x <- 1:dim(temp2021)[1]
  output$myplot <- renderPlot({
    plot.ts(get_ts(input$k,temp2021))
  })}

shinyApp(ui = ui, server = server)
